# fly.toml app configuration file generated for wee on 2023-08-07T14:25:37-10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wee"
primary_region = "lax"

[build]

[[mounts]]
  source = "wee_data_volume"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
